project:
  type: website

website:
  title: "Federica Gazzelloni's Website"
  description: "Data Science"
  favicon: images/profile.png
  site-url: https://federicagazzelloni.com
  repo-url: https://github.com/fgazzelloni
  repo-actions: [issue]
  cookie-consent:
    type: express
    style: headline
    palette: light
  google-analytics:
    tracking-id: "G-119NQB71C8"
    anonymize-ip: true
  open-graph: 
    locale: en_US
  twitter-card:
    creator: "@fgazzelloni"
  page-navigation: true
  back-to-top-navigation: true 
  reader-mode: true
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Health Metrics and the Spread of Infectious Diseases** is now available online! [Check it out](https://bookdown.org/fede_gazzelloni/hmsidR/)"
    type: danger
    position: below-navbar
  #body-header: | 
  #  This page brought to you by <https://federicagazzelloni.com>
  #margin-header: |
  #  ![FG](/images/profile.png)
  body-footer: | 
    Contacts and Information: <fede.gazzelloni@gmail.com>
  #margin-footer: |
  #  ![FG](/images/profile.png)  
  navbar: 
    right:
      - text: "Data Visualization"
        href: content/dataviz/index.qmd
      - text: "Statistics"
        href: content/stats/index.qmd
      - text: "Projects"
        href: content/proj/index.qmd
     # - text: "R-Ladies"
     #   href: posts/rladies/index.qmd
      - text:  "About"
        href: about.qmd
      - text: "{{< ai orcid size=xl >}}"
        href: https://orcid.org/0000-0002-4285-611X
      - icon: github
        href: https://github.com/fgazzelloni
      - text: "{{< ai google-scholar size=xl >}}"
        href: https://scholar.google.com/citations?hl=en&user=Xes0-r0AAAAJ
      - icon: rss
        href: index.xml  
  page-footer:
    left: "© Copyright &copy; CC-By [Federica Gazzelloni](https://github.com/Fgazzelloni). CC-BY-NC 4.0."
    right: 
      - text: "This Blog is made with 💜 in Quarto"
        href: "https://quarto.org"
      - icon: github
        href: https://github.com/fgazzelloni
      - icon: twitter 
        href: https://twitter.com/fgazzelloni 
lang: en    
format:
  html:
    smooth-scroll: true
    theme: sandstone
    css: styles.css
    toc: true
    link-external-icon: false
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    code-link: true
    code-overflow: wrap
    title-block-banner: true
    page-navigation: true
    back-to-top-navigation: true
    #include-in-header: 
     # - text: |
      #    <script src="https://cdn.jsdelivr.net/npm/typeit@7.0.4/dist/typeit.min.js">


editor: visual
execute: 
  freeze: auto

